---
- name: daemon-reload
  shell: |
    systemctl daemon-reload
- name: restarted_kafka
  service: 
    name: kafka
    state: restarted
  when: ansible_os_family == "Debian"

- name: restarted_zookeeper
  service: 
    name: zookeeper
    state: restarted
  when: ansible_os_family == "Debian"