---
- name: apache2
  hosts: all
  become: true

  vars:
    source_folder: ./MYSITE/
    destin_folder: /var/www/html

  tasks:
    - name: проверка семейства oc linux
      debug:
        var: ansible_os_family


    - block: #=========block UBUNTU=======
        - name: установка apache2 на UBUNTU
          apt:
            name: apache2
            state: present           


        - name: включаем apache2 на UBUNTU
          service: 
            name: apache2
            state: started
            enabled: true
      when: ansible_os_family == "Debian"


    - block: #=========block UBUNTU=======
        - name: установка apache (httpd) на RedHat
          yum:
            name: httpd
            state: present

        - name: включаем apache (httpd) на RedHat
          service: 
            name: httpd
            state: started
            enabled: true
      when: ansible_os_family == "RedHat"

    - name: копировать мой сайт "UBUNTU"
      copy:
        src: "{{ source_folder }}"
        dest: "{{ destin_folder }}"
 
#    - name: копировать мой сайт "UBUNTU"
#      copy: src={{ item }}  dest={{ destin_folder }} mode=0555
#      with_fileglob: "{{ source_folder }}/*.*"   #альторнатива этому loop ниже указано
#      copy: src={{ source_folder }}/{{ item }}  dest={{ destin_folder }} mode=0555
#      loop:
#        - "index.html"
#        - "text.css"
#        - "text.react.css"
      notify: 
        - restart_apache2_UBUNTU
        - restart_apache2_RedHat



  handlers:
  - name: restart_apache2_UBUNTU
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"

  - name: restart_apache2_RedHat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"