---
- name: установка apache2
  hosts: all
  tasks:
    - name: apache2
      apt:
        name: apache2
        state: present
    - name: start apach2
      service: name=apache2 state=started enabled=true
  become: true