---
- name: my playbook for variables
  hosts: all
  become: true

  vars:
    message: hello
    message2: secret
    secret: hello hell


  tasks:
    - name: prin sectet variables
      debug: 
        var: secret

    - debug:
        msg: "secretnoe slovo {{ secret }}"

    - debug:
        msg: "vladelic etogo servera -->{{ owner }}<--"

    - set_fact: full_msg="{{ message }} {{ message2 }}  from {{ owner }}"

    - debug:
        var: full_msg

    - debug:
        var: ansible_distribution